# Visit https://docs.keel.so/authentication/getting-started for more information about authentication
auth:

# Visit https://docs.keel.so/envvars for more information about environment variables
environment:

# Visit https://docs.keel.so/secrets for more information about secrets
secrets:
  - name: SLACK_TOKEN
  - name: CHANNEL_ID
  - name: OPENAI_KEY
  - name: PLAIN_API_KEY
